Numpy :
Numpy is a fundamental library for scientific computing in python.it provides support for arrays and matrics along with a collection of mathematical functions to operate on these data structures.

In [1]:
!pip install numpy


In [2]:
import numpy as np


In [4]:
## create arrays
##create 1d array
arr1=np.array([1,2,3,4,5])

In [5]:
print(arr1)

[1 2 3 4 5]


In [6]:
print(arr1.shape)

(5,)


In [10]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)## 1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [11]:
arr2=np.array([[1,2,3,4,5]])

In [12]:
arr2.shape

(1, 5)

In [13]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])## 2d array

In [14]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
arr2.shape

(2, 5)

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,10,2).reshape(5,1)## 5 rows

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.arange(0,10,2).reshape(1,5)## 5 columns

array([[0, 2, 4, 6, 8]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
## atrtributes of array
arr=np.array([[1,2,3,4,5],[2,6,7,8,9]])
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (Number of elements):",arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3 4 5]
 [2 6 7 8 9]]
Shape: (2, 5)
Number of dimensions: 2
Size (Number of elements): 10
Data type: int32
Item size (in bytes): 4


In [25]:
## numpy vectorized Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
## element wise adddition
print("Addition: ", arr1+arr2)

## element wise subtraction
print('Subtraction: ',arr1-arr2) 

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]


In [26]:
## unverisal function
arr=np.array([1,2,3,4,5])
## sqrt root
print(np.sqrt(arr))
## exponential
print(np.exp(arr))
## Sine
print(np.sin(arr))
## natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [28]:
# Array slicing and indexing
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
array[0][2] 

3

In [34]:
array[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [35]:
array[0:2,2:]

array([[3, 4],
       [7, 8]])

In [36]:
array[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [37]:
## modiy element
array[1:,1:3]=[[12,13],[14,15]]

In [38]:
array

array([[ 1,  2,  3,  4],
       [ 5, 12, 13,  8],
       [ 9, 14, 15, 12]])

In [40]:
## Sataistical concepts-normaliziation
## to have a mean of 0 and standard devaition of 1
data = np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)
##normalize the data
normalized_data=(data-mean)/std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [42]:
## mean meadian mode
mean=np.mean(data)
median=np.median(data)
print(mean)
print(median)
std_dev=np.std(data)
variance=np.var(data)
print(std_dev)
print(variance)

3.0
3.0
1.4142135623730951
2.0


In [47]:
## logical operation
data=np.array([1,3,4,5,6,7,8])
data[data>5]
data[(data>3) & (data<7)]

array([4, 5, 6])